# Generated by Django 4.2.24 on 2025-09-25 09:17

from django.db import migrations, models
import otp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('otp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('exp', models.DateTimeField(default=otp.models.default_expiry)),
            ],
        ),
    ]
