# Generated by Django 4.2.24 on 2025-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=5)),
                ('active', models.BooleanField(default=False)),
                ('exp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ManyToManyField(to='COupon_code.couponcode')),
                ('user', models.ManyToManyField(to='profiles.profiles')),
            ],
        ),
    ]
