# Generated by Django 4.2.24 on 2025-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
