# Generated by Django 4.2.24 on 2025-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horoscope', '0002_horo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekHoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(max_length=100)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('horoscope', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('zodiac_sign', 'week_start')},
            },
        ),
    ]
