# Generated by Django 4.2.24 on 2025-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horoscope', '0003_weekhoro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthHoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(max_length=100)),
                ('month_start', models.DateField()),
                ('month_end', models.DateField()),
                ('horoscope', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('zodiac_sign', 'month_start')},
            },
        ),
    ]
