# Generated by Django 4.2.24 on 2025-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horoscope', '0004_monthhoro'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearHoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('horoscope', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('zodiac_sign', 'year')},
            },
        ),
    ]
