# Generated by Django 4.2.24 on 2025-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='homepage/headerBanner')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Middle_2_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='homepage/middle_2_Banner')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='homepage/middleBanner')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='homepage/VideoSection')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WayToSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homepage/middleBanner')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
